/**
 * Alias MANUAL de nombres de baremo -> nombre canónico del catálogo.
 *
 * A diferencia de `standardization-map.ts` (auto-generado desde
 * ESTANDARIZACION-BAREMOS.md y espejado por la migración
 * StandardizeServiceTypeNames), este archivo SÍ se edita a mano y sólo lo
 * consume el seeder de baremos: no renombra nada en la base, únicamente
 * resuelve el nombre crudo de un Excel al tipo de servicio ya existente.
 *
 * Se aplica ANTES del mapa de estandarización dentro de `canonicalName()`.
 * Clave = nombre tal cual viene del Excel (se compara sin acentos/mayúsculas).
 * Valor = nombre canónico del catálogo.
 *
 * Origen actual: BAREMOS OCEANICA.xlsx (jul-2024). Los nombres que NO están
 * aquí se crean como tipos de servicio nuevos con el nombre del Excel.
 */
export const BAREMO_NAME_ALIASES: Record<string, string> = {
  // --- Consultas ---
  'GINECOLOGIA Y OBSTETRICIA': 'CONSULTA: GINECOLOGÍA Y OBSTETRICIA',
  'PEDIATRIA GENERAL': 'CONSULTA: PEDIATRÍA',
  'TRAUMATOLOGIA Y ORTOPEDIA': 'CONSULTA: TRAUMATOLOGÍA',

  // --- Hematología / coagulación ---
  'HEMOGRAMA TIPO I- (HEMATOLOGIA COMPLETA)': 'HEMATOLOGÍA COMPLETA',
  'HEMOPARASITOS EN GOTA GRUESA': 'GOTA GRUESA (PALUDISMO)',
  'TIEMPO PARCIAL DE TROMBOPLASTINA TPT': 'TIEMPO DE TROMBOPLASTINA PARCIAL (PTT)',
  'TIEMPO DE PROTOMBINA PT': 'TIEMPO DE PROTROMBINA (PT)',
  'FIBRINOGENO POR COAGULACION': 'FIBRINÓGENO',
  'HEMOCLASIFICACION GRUPO SANGUINEO Y FACTOR RH': 'GRUPO SANGUÍNEO ABO Y FACTOR RH',
  'DIMERO D EIA': 'DIMERO D',

  // --- Química ---
  'CREATIN QUINASA FRACCION CARDIACA - CK-MB-POR MASA': 'CKMB',
  'CREATIN QUINASA TOTAL-CK-CPK-': 'CK TOTAL',
  'DESHIDROGENASA LACTICA -LDH-': 'LDH (DESHIDROGENASA LÁCTICA)',
  'HEMOGLOBINA GLICOSILADA ANTICUERPOS MONOCLONALES': 'HEMOGLOBINA GLICOSILADA (HbA1C)',
  'TROPONINA T CUALITATIVA -PRUEBA RAPIDA-': 'TROPONINA T (cTnT)',
  'CAPACIDAD TOTAL DE FIJACION DEL HIERRO -TIBC TOTAL IRON-BINDING CAPACITY -':
    'CAPACIDAD DE FIJACIÓN DE HIERRO',
  'SATURACION DE LA TRANSFERRINA -INCLUYE DETERMINACION DE HIERRO SERICO CAPACIDAD TOTAL DE':
    'SATURACIÓN DE TRANSFERRINA',
  'TRANSFERRINA IDR': 'TRANSFERRINA',
  'COLESTEROL V L D L': 'COLESTEROL VLDL',
  'COLESTEROL ALTA DENSIDAD -HDL-': 'COLESTEROL HDL',
  'COLESTEROL BAJA DENSIDAD -LDL- CALCULADO ENZIMATICO': 'COLESTEROL LDL',
  'BILIRRUBINA TOTAL Y DIRECTA': 'BILIRRUBINA TOTAL Y FRACCIONADA',
  'GAMA GLUTAMIL TRANSFERASA-GGT-': 'GGT (GAMMA GLUTAMIL TRANSPEPTIDASA)',
  'TRANSAMINASA PIRUVICA ALAT': 'TGP / ALT',
  'ALFA FETOPROTEINA MATERNA': 'ALFAFETOPROTEÍNA (AFP)',

  // --- Hormonas / marcadores tumorales ---
  ESTROGENOS: 'ESTROGENO',
  'PROLACTINA -MUESTRA UNICA-': 'PROLACTINA',
  'HORMONA ESTIMULANTE DEL TIROIDES -TSH-': 'TSH',
  'HORMONA FOLICULO ESTIMULANTE -FSH-': 'FSH',
  'HORMONA LUTEINIZANTE -LH-': 'LH',
  'TIROXINA TOTAL -T4 TOTAL-': 'T4 TOTAL',
  'TRIYODOTIRONINA LIBRE -T3L-': 'T3 LIBRE',
  'TRIYODOTIRONINA TOTAL -T3 TOTAL -': 'T3 TOTAL',
  'GONADOTROPINA CORIONICA SUB-UNIDAD BETA CUALITATIVA-PRUEBA DE EMBARAZO':
    'PRUEBA DE EMBARAZO-HCG CUALITATIVA',
  'GONODOTROPINACORIONICA SUBUNIDAD BETA CUANTITATIVA': 'HCG CUANTITATIVA (BETA-HCG)',
  'ANTIGENO CARCINOEMBRIONARIO -ACE-CEA-': 'CEA (ANTÍGENO CARCINOEMBRIONARIO)',
  'ANTIGENO DE CANCER 125 -CA 125-': 'CA 125',
  'ANTIGENO DE CANCER 15-3 -CA 15-3-': 'CA 15-3',
  'ANTIGENO DE CANCER 19-9 -CA 19-9-': 'CA 19-9',
  'ANTIGENO ESPECIFICO DE PROSTATA AEP PSA-':
    'ANTÍGENO PROSTÁTICO ESPECÍFICO TOTAL (PSA TOTAL)',
  'ANTIGENO ESPECIFICO DE PROSTATA FRACCION LIBRE':
    'ANTÍGENO PROSTÁTICO ESPECÍFICO LIBRE (PSA LIBRE)',

  // --- Orina ---
  'AMILASA EN ORINA DE 24 HORAS': 'AMILASA EN ORINA 24H',
  'CLORO EN ORINA DE 24 HORAS': 'CLORO EN ORINA 24 HORAS',
  'FOSFORO INORGANICO -FOSFATOS- EN ORINA DE 24 HORAS': 'FÓSFORO EN ORINA 24 HORAS',
  'POTASIO EN ORINA DE 24 HORAS': 'POTASIO EN ORINA 24 HORAS',
  // el Excel rotula explicitamente las de 24h; sin rotulo = muestra parcial
  'SODIO EN ORINA': 'SODIO EN ORINA PARCIAL',
  'MICROALBUMINURIA NEFELOMETRIA': 'MICROALBUMINURIA',
  'ELECTROLITOS NA K CL EN ORINA': 'ELECTROLITOS EN ORINA',
  'ELECTROLITOS 24 HORAS': 'ELECTROLITOS EN ORINA 24 HORAS',
  // el catalogo tiene 'PROTEINURIA' (generica, la que se elige al facturar),
  // 'PROTEINURIA EN ORINA 24 HORAS' y la malformada 'PROTEINURIA EN ORINA
  // PARCIAL 24H'; la parcial de Oceanica va a la generica
  'PROTEINURIA PARCIAL': 'PROTEINURIA',
  'UROANALISIS-CITOQUIMICO DE ORINA- INCLUYE QUIMICA POR CUALQUIER METODO Y SEDIMENTO':
    'EXAMEN DE ORINA',
  'RELACION ACIDO CALCIO/CREATININA': 'RELACIÓN CALCIO/CREATININA EN ORINA',
  'RELACION ACIDO FOSFORO/CREATININA': 'RELACIÓN FÓSFORO/CREATININA',
  'RELACION ACIDO MAGNESIO/CREATININA': 'RELACION MAGNESIO/CREATININA',
  'RELACION ACIDO ALBUMINA/CREATININA': 'RELACION ALBUMINA/CREATININA',
  'RELACION ACIDO URICO CRATININA PARC':
    'RELACIÓN ÁCIDO ÚRICO/CREATININA EN ORINA PARCIAL',
  'RELACION DE ACIDO URICO CREATININA 24 HORAS':
    'RELACIÓN ÁCIDO ÚRICO/CREATININA EN ORINA 24 HORAS',

  // --- Inmunología / serología ---
  'ANTICUERPOS ANTI TIROIDEOS -MICROSAMALES- IHA':
    'ANTICUERPOS ANTI-TPO (ANTIMICROSOMALES)',
  'CARDIOLIPINAS FOSFOLIPIDOS PRUEBA CUANTITATIVA ANTICUR TIPO IGA IGG E IGM EIA':
    'CARDIOLIPINAS (FOSFOLIPIDOS) PRUEBA CUANTITATIVA ANTICUR TIPO IGA IGG E IGM',
  // el ST se llamaba "CHLAMYDIA TRACOMATI IGG"; migr 1782008800000 corrige el
  // typo. El nombre viejo viene del baremo de Seguros Venezuela (el IgM ya
  // estaba mapeado en standardization-map), así que también se redirige aquí
  // para que el seeder no vuelva a crear el ST mal escrito.
  'CHLAMYDIA TRACOMATI IGG': 'CHLAMYDIA TRACHOMATIS IgG',
  'CHLAMYDIA TRACHOMATIS ANTICUERPOS IGG EIA': 'CHLAMYDIA TRACHOMATIS IgG',
  'DENGUE ANTICUERPOS IG G': 'DENGUE IgG',
  'DENGUE ANTICUERPOS IG M': 'DENGUE IgM',
  'COMPLEMENTO SERICO FRACCION 3 -C3- IDR': 'COMPLEMENTO C3',
  'COMPLEMENTO SERICO-FRACCION 4- C4- IDR': 'COMPLEMENTO C4',
  'COMPLEMENTO TOTAL HEMOLITICO- CH50-': 'COMPLEMENTO CH50',
  'HERPES SIMPLEX I ANTICUERPOS IG G': 'HERPES SIMPLEX I IgG',
  'HERPES SIMPLEX I ANTICUERPOS IG M': 'HERPES SIMPLEX I IgM',
  'INMUNOGLOBULINA A -IGA- IDR': 'INMUNOGLOBULINA A (IgA)',
  'INMUNOGLOBULINA E TOTAL -IG E- RIA EIA': 'INMUNOGLOBULINA E (IgE)',
  'INMUNOGLOBULINA G -IG G- IDR': 'INMUNOGLOBULINA G (IgG)',
  'INMUNOGLOBULINA M -IG M- IDR': 'INMUNOGLOBULINA M (IgM)',
  'MYCOPLASMA PNEUMONIAE ANTICUERPOS IG G': 'MYCOPLASMA PNEUMONIAE IgG',
  'MYCOPLASMA PNEUMONIAE ANTICUERPOS IG M': 'MYCOPLASMA PNEUMONIAE IgM',
  'PROTEINA C REACTIVA CUANTITATIVA NEFELOMETRIA': 'PROTEÍNA C REACTIVA CUANTITATIVA',
  'PROTEINA C REACTIVA CUANLITATIVA LATEX': 'PROTEÍNA C REACTIVA (PCR)',
  'TOXOPLASMA GONDI ANTICUERPOS IG G EIA': 'TOXOPLASMA IgG',
  'TOXOPLASMA GONDII ANTICUERPOS IG M EIA': 'TOXOPLASMA IgM',
  'ANTICUERPOS ANTI DNA CADENA DOBLE': 'ANTICUERPOS ANTI DNA DOBLE CADENA (ELISA)',
  'HELICOBACTER PYLORI ANTICUERPOS IGG IGM E IGA EIA':
    'HELICOBACTER PYLORI ANTICUERPOS IGG IGM E IGA',
  'VDRL CUALITATIVIO': 'VDRL',
  'PROCALCITONINA SEMICUANTITATIVA': 'PROCALCITONINA',
  'TORCH IGG E IGM -TOXOPLASMA GONDII IGG E IGM RUBEOLA IGG E IGM CITOMEGALOVIRUS IGG E IGM':
    'PERFIL TORCH',
  'EPSTEIN-BARR ANTICUERPOS IGG CONTRA EL ANTIGENO CAPSULAR VCA-G IFI':
    'EPSTEIN-BARR IgG',
  'EPSTEIN-BARR ANTICUERPOS IGM CONTRA EL ANTIGENO CAPSULAR VCA-M IFI':
    'EPSTEIN-BARR IgM',
  'HEPATITIS A ANTICUERPOS IGM -ANTI-HVA-M-': 'ANTI-HAV IgM (HEPATITIS A)',
  // anticuerpos totales anti-HVA = IgG + IgM (no es solo el IgG)
  'HEPATITIS A ANTICUERPOS TOTALES -ANTI -HVA-': 'HEPATITIS A IgG + IgM',
  'HEPATITIS B ANTICUERPOS C IG M -ANTI-HBC-M-': 'ANTI-HBc IgM (HEPATITIS B)',
  'HEPATITIS B ANTICUERPOS C TOTALES -ANTI-HBC-': 'ANTI-HBc TOTAL (HEPATITIS B)',
  'HEPATITIS B ANTIGENO S- AG-HBS-': 'ANTÍGENO DE SUPERFICIE HEPATITIS B (HBsAg)',
  'HEPATITIS B ANTICUERPOS E -ANTI-HBE-': 'ANTI-HBe (HEPATITIS B)',
  'HEPATITIS C ANTICUERPOS -ANTI-HVC-': 'ANTI-HCV (HEPATITIS C)',

  // --- Cultivos / heces ---
  'CULTIVO DE MATERIA FECAL -COPROCULTIVO- INCLUYE IDENTIFICACION Y ANTIBIOGRAMA':
    'COPROCULTIVO',
  'CULTIVO SECRECION BRONQUIAL': 'CULTIVO Y ANTIBIOGRAMA DE SECRECIÓN BRONQUIAL',
  'CULTIVO ORINA': 'UROCULTIVO',
  'SANGRE OCULTA FECALES-PRUEBA GUAYACO O EQUIVALENTE': 'SANGRE OCULTA EN HECES',

  // --- Perfiles ---
  'PERFIL GENERAL O PERFIL 20': 'PERFIL 20',
  'PERFIL COAGULACION': 'PERFIL DE COAGULACION',
  // 'PERFIL FERROC. o ANEM. I/II' existe pero nadie lo elige por ese nombre:
  // el perfil de anemia de Oceanica va al ST que se usa en las ordenes
  'PERFIL ANEMIA I': 'PERFIL DE ANEMIA',

  // --- Radiología (el catálogo prefija "RX") ---
  'ARTICULACION 1 PROYECCION': 'RX ARTICULACION 1 PROYECCION',
  'ARTICULACION 2 PROYECCIONES': 'RX ARTICULACION 2 PROYECCIONES',
  'ARTICULACION 3 PROYECCIONES': 'RX ARTICULACION 3 PROYECCIONES',
  'ARTICULACION 4 PROYECCIONES': 'RX ARTICULACION 4 PROYECCIONES',
  'ARTICULACION 5 PROYECCIONES': 'RX ARTICULACION 5 PROYECCIONES',
  'ARTICULACION 6 PROYECCIONES': 'RX ARTICULACION 6 PROYECCIONES',
  'COLUMNA CERVICAL (A.P. LATERAL/OBLICUAS)': 'RX COLUMNA CERVICAL AP LAT OBLIC',
  'COLUMNA CERVICAL (AP YLATERAL )': 'RX COLUMNA CERVICAL AP LAT',
  'COLUMNA CERVICAL (LATERAL EN CAMA)': 'RX COLUMNA CERVICAL LATERAL EN CAMA',
  'COLUMNA CERVICAL (SOLO OBLICUAS)': 'RX COLUMNA CERVICAL OBLICUAS',
  'COLUMNA CERVICAL 3 PROYECCIONES': 'RX COLUMNA CERVICAL 3 PROYECCIONES',
  'COLUMNA CERVICAL 4 PROYECC.': 'RX COLUMNA CERVICAL 4 PROYECCIONES',
  'COLUMNA CERVICAL 5 PROYECCIONES': 'RX COLUMNA CERVICAL 5 PROYECCIONES',
  'COLUMNA CERVICAL 6 PROYECCIONES': 'RX COLUMNA CERVICAL 6 PROYECCIONES',
  'COLUMNA DORSAL 2 PROYECCIONE': 'RX COLUMNA DORSAL 2 PROYECCIONES',
  'COLUMNA DORSO LUMBAR AP': 'RX COLUMNA DORSO-LUMBAR AP',
  'COLUMNA DORSO-LUMBAR': 'RX COLUMNA DORSO-LUMBAR',
  'COLUMNA LUMBOSACRA': 'RX COLUMNA LUMBOSACRA',
  'COLUMNA LUMBAR 1 PROYECCION': 'RX COLUMNA LUMBAR 1 PROYECCION',
  'COLUMNA LUMBAR 2 PROYECCION': 'RX COLUMNA LUMBAR 2 PROYECCIONES',
  'COLUMNA LUMBAR 3 PROYECCION': 'RX COLUMNA LUMBAR 3 PROYECCIONES',
  'COLUMNA LUMBAR 4 PROYECCION': 'RX COLUMNA LUMBAR 4 PROYECCIONES',
  'RODILLA 2 PROYECCIONES': 'RX RODILLA 2 PROYECCIONES',
  'RODILLA AMBAS 2 PROYECCIONES': 'RX RODILLAS AMBAS 2 PROYECCIONES',
  'PIE 2 PROYECCIONES': 'RX PIE 2 PROYECCIONES',
  'PIE AMBOS 2 PROYECCIONES': 'RX PIES AMBOS 2 PROYECCIONES',
  'HOMBRO 2 PROYECCIONES': 'RX HOMBRO 2 PROYECCIONES',
  'HOMBRO AMBOS 2 PROYECCIONES': 'RX HOMBROS AMBOS 2 PROYECCIONES',
  'MANO 2 PROYECCIONES': 'RX MANO 2 PROYECCIONES',
  'MANO AMBAS 2 PROYECCIONES': 'RX MANOS AMBAS 2 PROYECCIONES',
  'MUÑECA 2 PROYECCIONES': 'RX MUÑECA 2 PROYECCIONES',
  'MUÑECA AMBAS 2 PROYECCIONES': 'RX MUÑECAS AMBAS 2 PROYECCIONES',
  'TOBILLO 2 PROYECCIONES': 'RX TOBILLO 2 PROYECCIONES',
  'TOBILLO AMBOS 2 PROYECCIONES': 'RX TOBILLOS AMBOS 2 PROYECCIONES',
  'SENOS PARANASALES': 'RX SENOS PARANASALES',
  'PELVIS AP': 'RX PELVIS AP',
  'PANORAMICA DE COLUMNA VERTEBRAL': 'RX PANORÁMICA DE COLUMNA VERTEBRAL',
  'TORAX 1 PROYECCION': 'RX TORAX 1 PROYECCION',
  'TORAX 2 PROYECCIONES': 'RX TORAX 2 PROYECCIONES',
  'TORAX 3 PROYECCIONES': 'RX TORAX 3 PROYECCIONES',
  'TORAX 4 PROYECCIONES': 'RX TORAX 4 PROYECCIONES',

  // --- Ecografías (el Excel trae punto final y "RIQONES" por "RIÑONES") ---
  'ECOGRAFIA OBSTETRICA.': 'ECOGRAFÍA OBSTÉTRICA',
  'ECOGRAFIA PELVICA O GINECOLOGICA.': 'ECOGRAFÍA PÉLVICA',
  'ECOGRAFIA DE VEJIGA': 'ECOSONOGRAMA VESICAL',
  'ECOGRAFIA VESICAL (VEJIGA)': 'ECOSONOGRAMA VESICAL',
  'ECOGRAFIA RIQONES.': 'ECOGRAFÍA RENAL',
  'ECOGRAFIA VIAS URINARIAS (RIQONES, VEJIGA Y PROSTATA TRANSABDOMINAL)':
    'ECOGRAFÍA DE VÍAS URINARIAS (RIÑONES, VEJIGA Y PRÓSTATA TRANSABDOMINAL)',
  'ECOGRAFIA TESTICULO.': 'ECOGRAFÍA TESTICULAR',
  'ECOGRAFIA TEJIDOS BLANDOS.': 'ECOGRAFÍA DE PARTES BLANDAS',
  'ECOGRAFIA OJO.': 'ECOGRAFIA OCULAR',
  'ECOGRAFIA CADERA PEDIATRICA.': 'ECOGRAFÍA DE CADERA PEDIÁTRICA',
  'ECOGRAFIA HOMBRO.': 'ECOGRAFÍA DE HOMBRO',
  'ECOGRAFIA RODILLA.': 'ECOGRAFÍA DE RODILLA',
  'ECOGRAFIA PROSTATA': 'ECOGRAFÍA PROSTÁTICA',
  'ECOGRAFIA MUSCULO ESQUEL': 'ECOGRAFÍA OSTEOMUSCULAR',
  'ECOGRAFIA TIROIDEO': 'ECOGRAFÍA TIROIDEA',
  'ECOGRAFIA ENCEFALOGRAMA': 'ECOGRAFÍA ENCEFÁLICA',
  'ECOGRAFIA ESPLENICO': 'ECOGRAFÍA ESPLÉNICA',
  'ECOGRAFIA PANCREATICO': 'ECOGRAFÍA PANCREÁTICA',
  'ECOGRAFIA PELVICO TRANPERIANAL': 'ECOGRAFÍA PÉLVICA TRANSPERINEAL',
  'ECOGRAFIA PROSTATICO TRANSVESICAL': 'ECOGRAFÍA PROSTÁTICA TRANSVESICAL',
  // dos codigos del seguro para el mismo estudio ($40 y $30): ambos al mismo ST
  // y el seeder se queda con el mayor (ver seedInsurancePrices)
  'ECOGRAFIA SUPRARRENAL': 'ECOGRAFÍA SUPRARRENAL',
  'ECOGRAFIA SUPRARENAL': 'ECOGRAFÍA SUPRARRENAL',
  'ECOGRAFIA TRANSRECTAL PARA MUCOSA': 'ECOGRAFÍA TRANSRECTAL DE MUCOSA',
  'ECOGRAFIA DE CADERA UNILATERAL': 'ECOGRAFÍA DE CADERA UNILATERAL',
  'ECOGRAFIA ARTICULAR': 'ECOGRAFÍA ARTICULAR',

  // --- Otros procedimientos ---
  'BIOPSIA MAS COLPOSCOPIA (VULVOSCOPIA)': 'BIOPSIA MAS COLPOSCOPIA VULVOSCOPIA',
  'MONITOREO DE TENSION ARTERIAL POR 24 HORAS (MAPA)':
    'MAPA (MONITOREO DE PRESIÓN ARTERIAL 24H)',
  'EXTRACCION CUERPO EXTRANO CONDUCTO AUDITIVO EXTERNO, SIN INCISION':
    'EXTRACCION CUERPO EXTRANO CONDUCTO AUDITIVO EXTERNO SIN INCISION',
  'CITOLOGIA GINECOLOGICA ©': 'CITOLOGIA GINECOLOGICA',
  'LAVADO DE OIDOS': 'LAVADO DE OÍDOS',

  // --- Nombres nuevos: sólo se limpia la escritura del Excel ---
  'PROTEINA S DE LA COAGULACION TOTAL': 'PROTEÍNA S DE LA COAGULACIÓN TOTAL',
  'VITAMINA D 1 25-DIHIDROXI': 'VITAMINA D 1,25-DIHIDROXI',
  // codigo 401020081, un solo codigo para basal o post-carga: ST propio 1:1 con
  // el codigo del seguro en vez de repartirlo entre GLICEMIA BASAL/POST-PRANDIAL
  'GLUCOSA BASAL O POST C U': 'GLUCOSA BASAL O POST CARGA',
  'ELECTROLITOS SANGRE ORINA': 'ELECTROLITOS EN SANGRE Y ORINA',
  'PERFIL HEPATITIS B C AGS HB ANTI-CORE ANTI HCV':
    'PERFIL HEPATITIS B Y C (HBsAg + ANTI-CORE + ANTI-HCV)',
  // 'Isolator' = sistema de hemocultivo por lisis-centrifugacion (bacterias,
  // hongos y micobacterias); el Excel lo trae con typos
  'CULTIVO ISOLACTER CACTERIA HONGO BK': 'CULTIVO ISOLATOR (BACTERIA, HONGO, BK)',
  'RECUENTO MINUTADO ORINA 3 H': 'RECUENTO MINUTADO EN ORINA (3 HORAS)',
  'PERFIL HEPATICO COMPLETO': 'PERFIL HEPÁTICO COMPLETO',
  // codigo 404030211: familia citologia/anatomia patologica (la 404030412 es
  // la citologia ginecologica), NO el uroanalisis (401090014, fila aparte)
  'ORINA CADA MUESTRA': 'CITOLOGÍA DE ORINA (CADA MUESTRA)',
};
